# ------------------------------------------
# Traefik Configuration
# ------------------------------------------

traefik:
  deployment:
    replicas: 1

  # Entrypoints configuration
  ports:
    traefik:
      port: 8080
      expose:
        default: true
      exposedPort: 8080
    web:
      port: 8000
      expose:
        default: true
      exposedPort: 80
    websecure:
      port: 8443
      expose:
        default: true
      exposedPort: 443
      tls:
        enabled: true

  # API and Dashboard
  api:
    dashboard: true
    insecure: true

  # Kubernetes providers
  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: false
      allowExternalNameServices: false
      allowEmptyServices: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: false
      allowEmptyServices: true
      publishedService:
        enabled: true

  service:
    enabled: true
    type: LoadBalancer

  # Logging
  logs:
    general:
      level: INFO
    access:
      enabled: false

  # Metrics
  metrics:
    prometheus:
      enabled: true

  additionalArguments:
    - "--ping"
    - "--api.dashboard=true"
    - "--api.insecure=true"
    - "--providers.kubernetesingress=true"
    - "--providers.kubernetescrd=true"

  # Security configuration
  securityContext:
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532

  podSecurityContext:
    fsGroup: 65532

  # Default resource allocation
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 300m
      memory: 150Mi
