# Production environment specific values for Spring Boot API
# Only environment-specific overrides - everything else comes from charts/runtime/spring-api/values.yaml

# Environment configuration
environment: prd
replicaCount: 5
springProfile: prd

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: spring-api.example.com
      paths:
        - path: /api
          pathType: Prefix
          port: 8080
        - path: /logs
          pathType: Prefix
          port: 8081
        - path: /soap
          pathType: Prefix
          port: 8082
  tls:
    - secretName: spring-api-prd-tls
      hosts:
        - spring-api.example.com

# Resource allocation (prod-specific)
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi 