image:
  repository: busybox
  tag: "stable"
  pullPolicy: IfNotPresent


# Ingress configuration
ingress:
  host: spring-api.inposti-devopsi.com
  paths:
    - path: /api
      pathType: Prefix
      port: 8080
    - path: /logs
      pathType: Prefix
      port: 8081
    - path: /soap
      pathType: Prefix
      port: 8082
  tls:
    - hosts:
        - spring-api.inposti-devopsi.com
      # TODO: Use cert-manager to automatically create the TLS secret
      secretName: spring-api-tls

# ------------------------------------------
# Deployment Configuration
# ------------------------------------------

# Resource allocation
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# ------------------------------------------
# ConfigMap Configuration
# ------------------------------------------

configMap:
  mountPath: "/app/config.json"
  subPath: "config.json"
  data:
    config.json: |
      {
        "logging": {
          "level": "INFO",
        }
      }

# ------------------------------------------
# Secret Configuration
# ------------------------------------------

secrets:
  - API_KEY
  - DB_PASSWORD
  - JWT_SECRET
  - ENCRYPTION_KEY

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

# Additional volume mounts (beyond configMap and secrets)
volumeMounts:
  []
  # Example:
  # - name: extra-config
  #   mountPath: /app/extra
  #   readOnly: true

# Additional volumes (beyond configMap and secrets)
volumes:
  []
  # Example:
  # - name: extra-config
  #   configMap:
  #     name: extra-config-map

# Node selector, tolerations, affinity
nodeSelector: {}
tolerations: []
affinity: {}
