# Basic ArgoCD Configuration
# This values.yaml provides a minimal, production-ready ArgoCD setup
argocd:

  # Global configuration
  global:
    # Set logging format (text or json)
    logging:
      format: "json"
      level: "info"

    # ArgoCD Server configuration
    server:
      # Replicas for high availability
      replicas: 2

    # Enable metrics
    metrics:
      enabled: true

# ArgoCD Apps configuration
argocd-apps:
  # Bootstrap applications that will manage all other resources
  applications:
    argocd:
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      project: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      source:
        path: argocd-instance
        repoURL: https://github.com/s3lcsum/inposti-devopsi.git
        targetRevision: main
        helm:
          version: v3
          valueFiles:
            - values.yaml
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

    argocd-applicationsets:
      namespace: argocd
      additionalLabels: {}
      project: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      source:
        path: argocd-applicationsets
        repoURL: https://github.com/s3lcsum/inposti-devopsi.git
        targetRevision: main
        directory:
          recurse: true
          jsonnet: {}
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        managedNamespaceMetadata:
          labels:
            layer: core
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

  # Bootstrap project for ArgoCD self-management
  projects:
    argocd:
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      additionalLabels: {}
      additionalAnnotations: {}
      description: ArgoCD Project for self-management
      sourceRepos:
        - 'https://github.com/s3lcsum/inposti-devopsi.git'
      destinations:
        - namespace: argocd
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      namespaceResourceBlacklist: []
      namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false
      roles:
        - name: argocd-admin
          description: Full access to ArgoCD project
          policies:
            - p, proj:argocd:argocd-admin, *, *, *, allow
          groups: []
