argocd:
  redis-ha:
    enabled: true

  redisSecretInit:
    enabled: false

  controller:
    replicas: 1

  server:
    replicas: 2

  repoServer:
    replicas: 2

  applicationSet:
    replicas: 2

  configs:
    # External cluster credentials for dev and prd environments
    clusterCredentials:
      dev-global-cluster-0:
        server: https://10.89.1.7:6443
        labels:
          environment: dev
          region: us-central1
        annotations:
          managed-by: argocd
          cluster-ip: "10.89.1.7"
        config:
          tlsClientConfig:
            insecure: true
      
      prd-global-cluster-5:
        server: https://10.89.1.8:6443
        labels:
          environment: prd
          region: us-central1
        annotations:
          managed-by: argocd
          cluster-ip: "10.89.1.8"
        config:
          tlsClientConfig:
            insecure: true
