


argocd:
  redis-ha:
    enabled: true

  redisSecretInit:
    enabled: false

  controller:
    replicas: 1

  server:
    replicas: 2

  repoServer:
    replicas: 2

  applicationSet:
    replicas: 2
