apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: runtime
  namespace: argocd
spec:
  generators:
    # Matrix generator: combine chart discovery with environments
    - matrix:
        generators:
          # Discover all runtime charts excluding the values directory
          - git:
              repoURL: https://github.com/s3lcsum/inposti-devopsi.git
              revision: HEAD
              directories:
                - path: charts/runtime/*
                - path: charts/runtime/values
                  exclude: true
          # Progressive deployment: dev first, then prod
          - list:
              elements:
                # Development environment (deploys first)
                - cluster: dev-global-cluster-0
                  url: https://10.89.1.7:6443
                  environment: dev
                  region: us-central1
                  priority: "1"
                # Production environment (deploys second)
                - cluster: prd-global-cluster-5
                  url: https://10.89.1.8:6443
                  environment: prd
                  region: us-central1
                  priority: "2"
  template:
    metadata:
      name: '{{`{{path.basename}}`}}-{{`{{environment}}`}}-{{`{{region}}`}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{`{{path.basename}}`}}'
        app.kubernetes.io/environment: '{{`{{environment}}`}}'
        app.kubernetes.io/component: runtime
        app.kubernetes.io/region: '{{`{{region}}`}}'
      annotations:
        # Progressive deployment annotation
        argocd.argoproj.io/sync-wave: '{{`{{priority}}`}}'
    spec:
      project: runtime
      source:
        repoURL: https://github.com/s3lcsum/inposti-devopsi.git
        targetRevision: HEAD
        path: '{{`{{path}}`}}'
        helm:
          valueFiles:
            - values.yaml
            - '../values/{{`{{environment}}`}}/{{`{{region}}`}}/{{`{{path.basename}}`}}.yaml'
      destination:
        server: '{{`{{url}}`}}'
        # Runtime applications go in environment-specific namespaces
        namespace: '{{`{{path.basename}}`}}-{{`{{environment}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        # Progressive deployment: wait for previous wave to be healthy
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 10