apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure applications project for core components like Traefik, cert-manager, etc.
  
  # Source repositories
  sourceRepos:
    - 'https://github.com/s3lcsum/inposti-devopsi.git'
  
  # Destination clusters and namespaces
  destinations:
    - namespace: 'infrastructure-*'
      server: https://10.89.1.7:6443
    - namespace: 'infrastructure-*'
      server: https://10.89.1.8:6443
    - namespace: 'traefik-*'
      server: https://10.89.1.7:6443
    - namespace: 'traefik-*'
      server: https://10.89.1.8:6443
    - namespace: 'cert-manager'
      server: https://10.89.1.7:6443
    - namespace: 'cert-manager'
      server: https://10.89.1.8:6443
  
  # Cluster resource allow list
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: storage.k8s.io
      kind: StorageClass
    - group: ''
      kind: PersistentVolume
  
  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: apps
      kind: DaemonSet
    - group: apps
      kind: StatefulSet
    - group: batch
      kind: Job
    - group: batch
      kind: CronJob
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: cert-manager.io
      kind: Certificate
    - group: cert-manager.io
      kind: ClusterIssuer
    - group: cert-manager.io
      kind: Issuer
  
  # Roles for RBAC
  roles:
    - name: developer
      description: Developer role with read access to infrastructure applications
      policies:
        - p, proj:infrastructure:developer, applications, get, infrastructure/*, allow
        - p, proj:infrastructure:developer, applications, sync, infrastructure/*, allow
      groups:
        - developers
    
    - name: admin
      description: Admin role with full access to infrastructure applications
      policies:
        - p, proj:infrastructure:admin, applications, *, infrastructure/*, allow
      groups:
        - admins 