apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-api.fullname" . }}
  labels:
    {{- include "spring-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      {{- include "spring-api.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      annotations:
        {{/* Automatic restart on config/secret changes */}}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "spring-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spring-api.serviceAccountName" . }}

      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{/* Image */}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--spring.profiles.active={{ .Values.environment }}"

          {{/* Ports */}}
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
            - name: logs
              containerPort: 8081
              protocol: TCP
            - name: soap
              containerPort: 8082
              protocol: TCP

          {{/* Environment variables */}}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}

            {{/* Pod metadata fields */}}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            {{/* Secret-based environment variables */}}
            {{- range $key, $config := .Values.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "spring-api.fullname" $ }}-secret
                  key: {{ $key }}
            {{- end }}

          {{/* Health checks */}}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{/* Resource allocation */}}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{/* Volume mounts */}}
          {{- if or .Values.configMap.enabled .Values.volumeMounts }}
          volumeMounts:
            {{/* ConfigMap volume mount */}}
            {{- if .Values.configMap.enabled }}
            - name: config-volume
              mountPath: {{ .Values.configMap.mountPath }}
              subPath: {{ .Values.configMap.subPath }}
            {{- end }}
            {{/* Additional volume mounts */}}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          {{/* Pre-stop hook */}}
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "wget http://localhost:8080/service/shutdown"

      {{/* Volumes */}}
      {{- if or .Values.configMap.enabled .Values.volumes }}
      volumes:
        {{/* ConfigMap volume */}}
        {{- if .Values.configMap.enabled }}
        - name: config-volume
          configMap:
            name: {{ include "spring-api.fullname" . }}-config
        {{- end }}

        {{/* Additional volumes */}}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}

      {{/* Node scheduling */}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
