apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-api.fullname" . }}
  labels:
    {{- include "spring-api.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "spring-api.selectorLabels" . | nindent 4 }}

  type: ClusterIP
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: logs
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: soap
      port: 8082
      targetPort: 8082
      protocol: TCP
